Repository PJECZ/pjecz-plataforma-web, pull requests merged in 2022-02, with the labels that each got.

#313 Ricval/citas
  cli/commands/cmd_citas.py
  plataforma_web/app.py
  plataforma_web/blueprints/cit_citas/__init__.py
  plataforma_web/blueprints/cit_citas/forms.py
  plataforma_web/blueprints/cit_citas/models.py
  plataforma_web/blueprints/cit_citas/templates/cit_citas/detail.jinja2
  plataforma_web/blueprints/cit_citas/templates/cit_citas/list.jinja2
  plataforma_web/blueprints/cit_citas/view.py
  plataforma_web/blueprints/cit_clientes/__init__.py
  plataforma_web/blueprints/cit_clientes/forms.py
  plataforma_web/blueprints/cit_clientes/models.py
  plataforma_web/blueprints/cit_clientes/templates/cit_clientes/detail.jinja2
  plataforma_web/blueprints/cit_clientes/templates/cit_clientes/list.jinja2
  plataforma_web/blueprints/cit_clientes/templates/cit_clientes/search.jinja2
  plataforma_web/blueprints/cit_clientes/views.py
  plataforma_web/blueprints/cit_dias_inhabiles/__init__.py
  plataforma_web/blueprints/cit_dias_inhabiles/forms.py
  plataforma_web/blueprints/cit_dias_inhabiles/models.py
  plataforma_web/blueprints/cit_dias_inhabiles/templates/cit_dias_inhabiles/detail.jinja2
  plataforma_web/blueprints/cit_dias_inhabiles/templates/cit_dias_inhabiles/edit.jinja2
  plataforma_web/blueprints/cit_dias_inhabiles/templates/cit_dias_inhabiles/list.jinja2
  plataforma_web/blueprints/cit_dias_inhabiles/templates/cit_dias_inhabiles/new.jinja2
  plataforma_web/blueprints/cit_dias_inhabiles/views.py
  plataforma_web/blueprints/cit_expedientes/__init__.py
  plataforma_web/blueprints/cit_expedientes/forms.py
  plataforma_web/blueprints/cit_expedientes/models.py
  plataforma_web/blueprints/cit_expedientes/templates/cit_expedientes/detail.jinja2
  plataforma_web/blueprints/cit_expedientes/templates/cit_expedientes/list.jinja2
  plataforma_web/blueprints/cit_expedientes/templates/cit_expedientes/search.jinja2
  plataforma_web/blueprints/cit_expedientes/views.py
  plataforma_web/blueprints/cit_servicios/__init__.py
  plataforma_web/blueprints/cit_servicios/forms.py
  plataforma_web/blueprints/cit_servicios/models.py
  plataforma_web/blueprints/cit_servicios/templates/cit_servicios/detail.jinja2
  plataforma_web/blueprints/cit_servicios/templates/cit_servicios/edit.jinja2
  plataforma_web/blueprints/cit_servicios/templates/cit_servicios/list.jinja2
  plataforma_web/blueprints/cit_servicios/templates/cit_servicios/new.jinja2
  plataforma_web/blueprints/cit_servicios/views.py
  plataforma_web/blueprints/distritos/models.py
  plataforma_web/blueprints/domicilios/__init__.py
  plataforma_web/blueprints/domicilios/forms.py
  plataforma_web/blueprints/domicilios/models.py
  plataforma_web/blueprints/domicilios/templates/domicilios/detail.jinja2
  plataforma_web/blueprints/domicilios/templates/domicilios/edit.jinja2
  plataforma_web/blueprints/domicilios/templates/domicilios/list.jinja2
  plataforma_web/blueprints/domicilios/templates/domicilios/new.jinja2
  plataforma_web/blueprints/domicilios/templates/domicilios/search.jinja2
  plataforma_web/blueprints/domicilios/views.py
  plataforma_web/blueprints/oficinas/__init__.py
  plataforma_web/blueprints/oficinas/forms.py
  plataforma_web/blueprints/oficinas/models.py
  plataforma_web/blueprints/oficinas/templates/oficinas/detail.jinja2
  plataforma_web/blueprints/oficinas/templates/oficinas/edit.jinja2
  plataforma_web/blueprints/oficinas/templates/oficinas/list.jinja2
  plataforma_web/blueprints/oficinas/templates/oficinas/new.jinja2
  plataforma_web/blueprints/oficinas/views.py
Labels: nuevo blueprint

#341 Varias mejoras
  plataforma_web/blueprints/soportes_tickets/forms.py
  plataforma_web/blueprints/soportes_tickets/models.py
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/categorize.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/detail.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list_cancel.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list_done.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list_no_resolve.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/new.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/take.jinja2
  plataforma_web/blueprints/soportes_tickets/views.py
Labels: enhancement

#347 AJAX en funcionarios.
  plataforma_web/blueprints/funcionarios/forms.py
  plataforma_web/blueprints/funcionarios/templates/funcionarios/list.jinja2
  plataforma_web/blueprints/funcionarios/templates/funcionarios/search.jinja2
  plataforma_web/blueprints/funcionarios/views.py
Labels: enhancement

#350 Estandarizar nombres, apellidos y puestos de los usuarios en mayusculas
  cli/commands/cmd_usuarios.py
  plataforma_web/blueprints/usuarios/tasks.py
Labels: enhancement

#354 Comando click para definir las oficinas de los usuarios
  cli/commands/cmd_usuarios.py
  plataforma_web/blueprints/usuarios/tasks.py
Labels: enhancement

#376 Ricval/detalles tickets
  plataforma_web/blueprints/soportes_categorias/views.py
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/detail.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/list_user.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/new.jinja2
  plataforma_web/blueprints/soportes_tickets/views.py
Labels: enhancement

#397 Mejoras en AJAX y reparaciones
  plataforma_web/blueprints/autoridades/templates/autoridades/detail.jinja2
  plataforma_web/blueprints/autoridades_funcionarios/templates/autoridades_funcionarios/list.jinja2
  plataforma_web/blueprints/funcionarios_oficinas/templates/funcionarios_oficinas/list.jinja2
  plataforma_web/blueprints/funcionarios_oficinas/views.py
  plataforma_web/blueprints/modulos/templates/modulos/detail.jinja2
  plataforma_web/blueprints/oficinas/templates/oficinas/detail.jinja2
  plataforma_web/blueprints/permisos/templates/permisos/list.jinja2
  plataforma_web/blueprints/permisos/views.py
  plataforma_web/blueprints/roles/templates/roles/detail.jinja2
  plataforma_web/blueprints/soportes_tickets/templates/soportes_tickets/detail.jinja2
  plataforma_web/blueprints/usuarios/templates/usuarios/detail.jinja2
  plataforma_web/blueprints/usuarios_roles/templates/usuarios_roles/list.jinja2
  plataforma_web/blueprints/usuarios_roles/views.py
Labels: bug
