Repository PJECZ/pjecz-plataforma-web, pull requests merged in 2023-09, with the labels that each got.

#726 Ricval/archivo btn historial
  plataforma_web/blueprints/arc_archivos/templates/arc_archivos/list_jefe_remesa.jinja2
  plataforma_web/blueprints/arc_archivos/views.py
Labels: bug

#744 Archio - crear expediente válidar juzgado por sede no por distrito
  plataforma_web/blueprints/arc_documentos/views.py
Labels: HotFix :fire:

#755 Quitar versiones y varias mejoras en inicio
  plataforma_web/blueprints/sistemas/templates/sistemas/start.jinja2
Labels: type: bug 🐛

#790 Archivo - Nuevas mejoras
  plataforma_web/blueprints/arc_archivos/CHANGELOG.md
  plataforma_web/blueprints/arc_archivos/templates/arc_archivos/list_archivista.jinja2
  plataforma_web/blueprints/arc_archivos/templates/arc_archivos/list_jefe_remesa.jinja2
  plataforma_web/blueprints/arc_archivos/templates/arc_archivos/list_solicitante.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/list_admin.jinja2
  plataforma_web/blueprints/arc_documentos/views.py
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail.jinja2
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail_archivista.jinja2
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail_solicitante.jinja2
  plataforma_web/blueprints/arc_remesas/views.py
  plataforma_web/blueprints/arc_remesas_documentos/views.py
Labels: develop :rocket:

#802 Archivo - Mensaje de advertencia en envío de remesa
  plataforma_web/blueprints/arc_archivos/CHANGELOG.md
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail_solicitante.jinja2
Labels: develop :rocket:

#803 Archivo - cambios listado expedientes
  plataforma_web/blueprints/arc_archivos/CHANGELOG.md
  plataforma_web/blueprints/arc_documentos/views.py
Labels: develop :rocket:

#810 Mejora de comentario
  plataforma_web/blueprints/arc_documentos/views.py
Labels: develop :rocket:

#811 Documentacion
  docs/archivo.md
  docs/fin_vales.md
  docs/img/fin-vales/crear_vale.png
  docs/img/fin-vales/editar_vale.png
  docs/img/fin-vales/impresion_vale.png
  docs/img/fin-vales/listado_vales.png
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
  requirements.txt
Labels: type: documentacion 📝, type: mejora ✨

#817 Requeriments change
  .gitignore
  requirements.txt
Labels: HotFix :fire:

#821 Archivo - Documentación de Arc_Documentos
  docs/arc_documentos.md
  docs/img/arc_documentos/Listado_tipos-documentos.png
  docs/img/arc_documentos/detalle_documento.png
  docs/img/arc_documentos/detalle_menu-principal.png
  docs/img/arc_documentos/listado_documentos.png
  docs/img/arc_documentos/listado_filtros.png
  docs/img/arc_documentos/listado_juzgados-extintos.png
  docs/img/arc_documentos/listado_menu-superior.png
  docs/img/arc_documentos/nuevo-documento-busqueda.png
  docs/img/arc_documentos/nuevo-documento.png
  docs/stylesheets/extra.css
Labels: type: documentacion 📝
