Repository PJECZ/pjecz-plataforma-web, pull requests merged in 2024-04, with the labels that each got.

#953 Archivo-mejoras-en-vista
  plataforma_web/blueprints/arc_archivos/templates/arc_archivos/list_jefe_remesa.jinja2
  plataforma_web/blueprints/arc_archivos/views.py
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail.jinja2
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail_archivista.jinja2
  plataforma_web/blueprints/arc_remesas/templates/arc_remesas/detail_solicitante.jinja2
Labels: type: mejora ✨

#954 Archivo - varios juzgados origen
  plataforma_web/blueprints/arc_documentos/forms.py
  plataforma_web/blueprints/arc_documentos/models.py
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/detail.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/detail_simple.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/edit.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/list_admin.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/new.jinja2
  plataforma_web/blueprints/arc_documentos/views.py
Labels: type: mejora ✨

#957 Archivo - cli juzgados origen
  cli/commands/cmd_arc_documentos.py
  plataforma_web/blueprints/arc_documentos/forms.py
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/edit.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/list_admin.jinja2
  plataforma_web/blueprints/arc_documentos/templates/arc_documentos/new.jinja2
  plataforma_web/blueprints/arc_documentos/views.py
  plataforma_web/blueprints/arc_juzgados_extintos/views.py
Labels: type: mejora ✨

#961 Archivo - Corrección de bug
  plataforma_web/blueprints/arc_documentos/views.py
Labels: type: bug 🐛, HotFix :fire:

#964 Exhortos - cli para alimentar estados y municipios
  cli/commands/cmd_estados.py
  cli/commands/cmd_municipios.py
  plataforma_web/blueprints/estados/models.py
Labels: type: mejora ✨

#966 Exhortos - estados y municipios vistas
  plataforma_web/blueprints/estados/templates/estados/detail.jinja2
  plataforma_web/blueprints/estados/templates/estados/list.jinja2
  plataforma_web/blueprints/estados/views.py
  plataforma_web/blueprints/municipios/templates/municipios/detail.jinja2
  plataforma_web/blueprints/municipios/templates/municipios/list.jinja2
  plataforma_web/blueprints/municipios/views.py
Labels: type: mejora ✨

#963 CidProcedimentos filtro procedimentos propios
  plataforma_web/blueprints/cid_procedimientos/views.py
Labels: type: bug 🐛

#973 Exhortos - Modelos
  plataforma_web/app.py
  plataforma_web/blueprints/exh_exhortos/__init__.py
  plataforma_web/blueprints/exh_exhortos/models.py
  plataforma_web/blueprints/exh_exhortos/views.py
  plataforma_web/blueprints/exh_exhortos_archivos/__init__.py
  plataforma_web/blueprints/exh_exhortos_archivos/models.py
  plataforma_web/blueprints/exh_exhortos_archivos/views.py
  plataforma_web/blueprints/exh_exhortos_partes/__init__.py
  plataforma_web/blueprints/exh_exhortos_partes/models.py
  plataforma_web/blueprints/exh_exhortos_partes/views.py
  plataforma_web/blueprints/materias/models.py
  plataforma_web/blueprints/municipios/models.py
Labels: type: mejora ✨
